[package]
name = "test-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
#tokio = { version = "1.0", features = ["full"] }

[dependencies.cursive]
version = "0.21"
default-features = false
features = ["crossterm-backend"]
